name: assets-export
on:
  schedule:
    - cron: "5 1 * * *"
  # push:
    # branches: [master]
    # paths: ["packages/datamine/scripts", "packages/datamine/src"]
  workflow_dispatch:

jobs:
  # windows must run this, not ubuntu, as pypoe/our datamine export depends on packages/datamine/ooz.exe
  fetch:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: git config --global core.safecrlf false
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile
      # no need to check versions first, it's a quick build
      - working-directory: ./packages/datamine
        run: yarn dist

      - run: echo "POE_VERSION=`cat packages/datamine/dist/version.txt`" | tee $GITHUB_ENV
      - run: git diff
      - run: git diff-index --quiet HEAD -- || echo "PYPOE_JSON_DIFF=1" | tee $GITHUB_ENV
      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      # if nothing's changed - the common case, when poe was not patched - this doesn't create a pr
      - if: ${{ github.event.inputs.force_build || env.PYPOE_JSON_DIFF != '' }}
        name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          title: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          body: >
            Looks like Path of Exile was patched recently! I've updated mapwatch for you. New version: ${{ env.POE_VERSION }}.

            This PR was auto-generated by the [assets-export robot](https://github.com/mapwatch/mapwatch/actions?query=workflow%3Aassets-export).
          labels: automated pr
